### ISSUE TITLE
Typegen fails when a Uuid is included

### ISSUE THREAD

**Issue by wasnotrice** [redbadger/crux#102]
I was trying to pass a `Uuid` value in an `Event` variant, but this breaks typegen. It seems like the typegen tries to create an "empty" Uuid, which doesn't work.

I've created a minimal reproduction in the counter example app in [this commit](https://github.com/wasnotrice/crux/commit/765b90dbd44ab139d3cfb9b3919a2629c52df364) on [this branch](https://github.com/wasnotrice/crux/tree/shared_types-uuid). I don't think it matters where the Uuid appears in the types registered with typegen.

Any ideas about how to tweak the typegen to handle Uuids?

**Comment by charypar** [comment]
I don't know whether it is the cause of this issue, but you might need to add `Uuid` into `build.rs` in the `shared_types` as a named type, so it gets registered.

**Comment by wasnotrice** [comment]
Thanks for the suggestion! I tried registering `Uuid` in `build.rs` like this

```
    gen.register_type::<Uuid>()?;
```

but still got the same error.

**Comment by charypar** [comment]
I looked at how `crux_core` itself uses uuid, and it doesn't have the `serde` feature enabled. Although upon closer inspection, we convert it to bytes manually 🤔 I can't remember, but we may have hit a similar problem in the past.

**Comment by charypar** [comment]
I suspect this might be down to our somewhat simplistic approach to the type tracing. Looks like the the error comes from here https://github.com/zefchain/serde-reflection/blob/1196fbe4c22b0842de4ced0974944d667c22816d/serde-reflection/src/trace.rs#L140

It seems likely that the samples for tracing it guess are invalid

**Comment by charypar** [comment]
There's even a note about this here https://github.com/zefchain/serde-reflection/blob/1196fbe4c22b0842de4ced0974944d667c22816d/serde-reflection/src/trace.rs#L130-L133

**Comment by charypar** [comment]
Ok so thinking about this a bit more, we probably need to expose a typegen API with support for value samples to get around this issue. At least until we maybe solve it with custom typegen (but somehow I suspect we may hit the same fundamental problem).

/cc @StuartHarris

**Comment by wasnotrice** [comment]
> I suspect this might be down to our somewhat simplistic approach to the type tracing

Yes, I agree.

I ran into a different typegen issue today as well, with a type that had `#[serde(into = "String")]`. It doesn't seem to be exactly the case in [that comment](https://github.com/redbadger/crux/issues/102#issuecomment-1516605603), but still related. 

These typegen errors are super cryptic and hard to track down. Is it helpful if I open specific issues for each case I run into? Or is it better to consolidate them?

I could also experiment with an additional typegen API that allows samples and see how that works.

**Comment by charypar** [comment]
Specific issues are probably better, but feel free to link them together as related.

And yes, by all means look at adding a typegen API with samples, especially if it lets you resolve the issues
