### ISSUE TITLE
Android shared_types can have stale/obsolete files

### ISSUE THREAD

**Issue by wasnotrice** [redbadger/crux#108]
For discussion: I expect the `shared_types` directory in my Android project to always exactly match the `shared_types/generated/java` directory.

As I've been refactoring my app, though, I've noticed that once a generated file is copied into the `shared_types` directory in my Android project, it never goes away, even if the corresponding file in `shared_types/generated/java` goes away, because the "standard" Android task never deletes anything.

I know this is a project-specific build task, but I wonder if it makes sense to update the suggested snippet. If I modify the Android `typesGen` task like this, I get my expected results. It might not be best to use `rsync` for the general case, but this is just an illustration of how I expect the task to work (I had to be more specific about the paths or this task would also delete `shared/shared.kt`).

```groovy
task typesGen(type: Exec) {
    def noviPackagePath = "com/novi"
    def sharedTypesPackagePath = "com/path/to/my/shared_types"
    def outDir = "${projectDir}/src/main/java"
    def srcDir = "shared_types/generated/java"
    workingDir "../../"
    commandLine(
            "sh", "-c",
            """\
            rsync -av --delete $srcDir/$noviPackagePath/ $outDir/$noviPackagePath/ && \
            rsync -av --delete $srcDir/$sharedTypesPackagePath/ $outDir/$sharedTypesPackagePath/ \
            # cp -r $srcDir $outDir <-- the current script
            """
    )
}
```

**Comment by StuartHarris** [comment]
Good spot! Thanks @wasnotrice :-) I'll raise a PR for this
