### ISSUE TITLE
How to handle errors in capabilities?

### ISSUE THREAD

**Issue by matthewpflueger** [redbadger/crux#130]
Hi, I am reading the docs and it isn't apparent how one should handle errors when writing custom capabilities. Do you all have a preferred architecture?

For example, I have a db capability that is pretty much ripped from the simple capabilities in crux (kv, time, etc - I posted the code below). Currently my db capability is such that the DbResponse is always successful (```pub struct DbResponse(pub Vec<u8>);``` - see below). But really, I'd like to establish some way to handle errors so I am thinking something along the lines of changing my response to something like:

```rust
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct DbError {
    statement: String,
    params: Vec<String>,
    error_code: u32,
    error_message: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
enum DbResponse {
    Data(Vec<u8>),
    Error(DbError),
}
```
Anyway, wondering what your thoughts are on the matter. Any advice greatly appreciated...

Thanks!

The simple db capability...

```rust
use crux_macros::Capability;
use serde::{Deserialize, Serialize};

use crux_core::capability::{CapabilityContext, Operation};
use serde::de::DeserializeOwned;

/// Capability ripped from https://github.com/redbadger/crux/blob/master/crux_kv/src/lib.rs

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq)]
pub struct DbRequest {
    pub statement: String,
    pub params: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DbResponse(pub Vec<u8>);

impl Operation for DbRequest {
    type Output = DbResponse;
}

#[derive(Capability)]
pub struct Db<Ev> {
    context: CapabilityContext<DbRequest, Ev>,
}

impl<Ev> Db<Ev>
where
    Ev: 'static,
{
    pub fn new(context: CapabilityContext<DbRequest, Ev>) -> Self {
        Self { context }
    }

    pub fn run<F, T>(&self, statement: &str, params: Vec<String>, make_event: F)
    where
        F: Fn(T) -> Ev + Send + Sync + 'static,
        T: DeserializeOwned,
    {
        let ctx = self.context.clone();
        let statement = statement.to_string();
        self.context.spawn(async move {
            let DbResponse(res) = ctx
                .request_from_shell(DbRequest { statement, params })
                .await;
            // TODO handle a DbResponse that is an error...
            let t: T = serde_json::from_slice(res.as_slice()).unwrap();
            ctx.update_app(make_event(t));
        });
    }
}

```

**Comment by charypar** [comment]
Hi @matthewpflueger, thanks for giving Crux a try! 

What you're suggesting looks right to me. The type generation will export your `DbResponse` type for you into the shell language, where you can create it and serialise it. 

It would be a hair nicer if the capability operation output could be a `Result<Output, Error>`, but, unfortunately, we've hit limitations of our current foreign type generation strategy that stop us doing that - in short it doesn't support generics. We have a few ideas, and are planning to look at that at some point in the future, but until then, your approach is (at least in my mind) the one we'd suggest. I suppose if you wanted to, your `run` API could take two different continuation event variant constructors, one for success, one for failure, but havig one and pattern matching on the `DbResponse` works just as well. Hope that helps! 

Any thoughts, @StuartHarris @obmarg? 

Btw, I'd be very keen to follow how your DB capability evolves, if it's possible somewhere public (or maybe comment on this when you get further with it?).

**Comment by wasnotrice** [comment]
@matthewpflueger I have a capability in my app like this (except it writes blobs to files instead of statements to a database). This pattern works well 👍

**Comment by matthewpflueger** [comment]
Thanks @charypar for the feedback! I will post more about my db capability and see about making it available publicly once it is further along.

@wasnotrice - Thanks for confidence boost! Indeed, this approach seems to be working well so far!
