### ISSUE TITLE
swift tools version, Package.swift

### ISSUE THREAD

**Issue by anvlkv** [redbadger/crux#152]
Would be great to be able to override or otherwise adjust the contents of the generated package. For example I need to use a different version of swift tool.

https://github.com/redbadger/crux/blob/ebfe6affb8aa3d588a75b6f496590a60733cacf4/crux_core/src/typegen.rs#L333

I'd be happy to work on a PR for this

**Comment by StuartHarris** [comment]
Hey, apologies for slow response. You would be more than welcome to submit a PR :-) Thank you

**Comment by anvlkv** [comment]
Thanks!

What approach should I take?

I thought it could use a template file. Or use a custom path provided by the user.

Op do 9 nov. , Stuart Harris ***@***.***(mailto:Op do 9 nov.  , Stuart Harris <<a href=)> schreef:

**Comment by charypar** [comment]
Not having thought about this very deeply, I'd go the way of attempting to allow custom code to be prepended/injected in the generated code, via an API call from the `build.rs` script in the types crate.

Not sure it covers all the necessary options. Do let us know what you find if you attempt it!

**Comment by anvlkv** [comment]
Hi Victor,

Please see my related PR. https://github.com/redbadger/crux/pull/157

Please let me know if I should change it to make an API call instead

Op wo 27 dec , Viktor Charypar ***@***.***(mailto:Op wo 27 dec  , Viktor Charypar <<a href=)> schreef:
