### ISSUE TITLE
Getting started instructions fail as missing workspace members

### ISSUE THREAD

**Issue by NukeManDan** [redbadger/crux#210]
I am all for including the source rather than using MD examples of code that might be missed in testing that are used in https://github.com/redbadger/crux/blob/master/docs/src/getting_started/core.md but sadly the cargo workspace includes members that are not yet present when trying to build `shared` with `cargo run -p shared --bin uniffi-bindgen`

I am not sure if it's worth maintaining a step-wise version that comments out or omits the members... but maybe worth mentioning in the walkthrough?

**Comment by NukeManDan** [comment]
Same latter with `crux_http.workspace = true` in `shared_types`

**Comment by StuartHarris** [comment]
Thanks, @NukeManDan — you're right, it is confusing. I'll update the docs accordingly.
