### ISSUE TITLE
counter example installation fails due to missing pnpm

### ISSUE THREAD

**Issue by guofoo** [redbadger/crux#84]
Following the steps here:
https://github.com/redbadger/crux/blob/master/examples/counter/README.md

Got an error at step 3:

     Blocking waiting for file lock on build directory
     Compiling getrandom v0.2.8
     Compiling rand_core v0.6.4
     Compiling uuid v1.3.0
     Compiling rand_chacha v0.3.1
     Compiling rand v0.8.5
     Compiling phf_generator v0.10.0
     Compiling phf_macros v0.10.0
     Compiling phf v0.10.1
     Compiling serde-generate v0.25.0
     Compiling crux_core v0.3.0 (/Users/guofoo/git/crux/crux/crux_core)
     Compiling crux_http v0.2.0 (/Users/guofoo/git/crux/crux/crux_http)
     Compiling crux_platform v0.1.1 (/Users/guofoo/git/crux/crux/crux_platform)
     Compiling crux_kv v0.1.1 (/Users/guofoo/git/crux/crux/crux_kv)
     Compiling crux_time v0.1.1 (/Users/guofoo/git/crux/crux/crux_time)
     Compiling shared v0.1.0 (/Users/guofoo/git/crux/crux/examples/counter/shared)
     Compiling shared_types v0.1.0 (/Users/guofoo/git/crux/crux/examples/counter/shared_types)
    error: failed to run custom build command for `shared_types v0.1.0 (/Users/guofoo/git/crux/crux/examples/counter/shared_types)`
    Caused by:
      process didn't exit successfully: `/Users/guofoo/git/crux/crux/examples/counter/target/debug/build/shared_types-07e3345a7cc49a79/build-script-build` (exit status: 101)
      --- stdout
      cargo:rerun-if-changed=../shared
      --- stderr
      thread 'main' panicked at 'Could not pnpm install: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/guofoo/git/crux/crux/crux_core/src/typegen.rs:252:14
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    ➜ ~/git/crux/crux/examples/counter/shared_types :(master)
_
So I installed pnmp and ran cargo run again, and everything proceeded normally.

**Comment by StuartHarris** [comment]
Thanks @guofoo! Yeah, we should mention this in (at least) the Readme. I _think_ it's OK for an example to depend on pnpm, but we should deffo call that out. Feel free to submit a PR, or we'll get to it ourselves soon.

**Comment by carltongibson** [comment]
FWIW I hit this too. Calling it out would be good.

**Comment by StuartHarris** [comment]
I realised we also depend on it during the typegen for TypeScript. Which is not good. But we're revisiting the type gen as we speak so the dependency on `pnpm` should disappear. In the meantime I updated the relevant readme files.
